mysqldb:
    type: mysql:10.0
    disk: 2048
    configuration:
        schemas:
            - myddleware
            - test
        endpoints:
            mysql:
              default_schema: myddleware
              privileges:
                myddleware: admin
                test: admin
